const array = [4, 5, 6, 7, 8, 9, 10];
let result = array.splice(1, 3, 14, 15);
console.log(result);
console.log(array);
const newArray = [1, 2, 3, 4, 5];
const result2 = newArray.shift();
console.log(result2);
console.log(newArray);
let result3 = newArray.unshift();
console.log(result3);
console.log(newArray);
